[vms]
vm-tls-nemo-app

[all:vars]
ansible_ssh_common_args='-F ./sshconfig'
# Ansible still expects a username; with az-ssh+AAD it’s often ignored because
# a proxy is used, but set something harmless:
ansible_user=azureuser